### ISSUE TITLE
テーマ：プリセット以外の配色が設定できるか調べてみましょう

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/mkdocs-material-sandbox#16]

**Comment by KATO-Hiro** [comment]
- Jekyllのテーマの一つ

```css
.page-header {
  color: #fff;
  text-align: center;
  background-color: #159957;
  background-image: linear-gradient(120deg, #155799, #159957); }
```
